### ISSUE TITLE
Cannot detect key presses that are handled by window manager

### ISSUE THREAD

**Issue by blokeley** [microsoft/winrt-rs#124]
Some key presses are handled by the Windows' window manager, such as <kbd>Win</kbd>+<kbd>x</kbd>.

Is it possible to:
1. Detect those key presses?
2. Prevent the window manager from processing them?

Example code: If a `winit::event::DeviceEvent::Key` is detected, pass it to the following function:

```rust
pub fn on_key_event(input: KeyboardInput) {
    if input.state != ElementState::Pressed {
        return;
    }
    println!("{:?} + {:?}", input.modifiers, input.virtual_keycode);
}
```

**Comment by jdm** [comment]
Did you mean to file this in https://github.com/rust-windowing/winit/?

**Comment by blokeley** [comment]
I thought that it might be a Windows-specific issue so might only appear in `winrt-rs`.  If it's a `winit` level limitation, please let me know and I'll consider filing an issue there.  It may be related to the [raw device events discussion](https://github.com/rust-windowing/winit/issues/750).

**Comment by robmikh** [comment]
Agreed, this seems to be a question directed at winit rather than Rust/WinRT.

FWIW, I'd advise against overriding system hotkeys. I also don't believe there's a way to prevent the system from receiving the keys. If you *really* need to detect the key-press for some reason, you should look into `SetWindowsHookExW`. However it won't stop the system from responding to it as well.
