### ISSUE TITLE
how to use Clipboard.GetContent in winrt-rs

### ISSUE THREAD

**Issue by Pointime** [microsoft/winrt-rs#187]
I don't know how to find the documentation of winrt-rs

**Comment by kennykerr** [comment]
Generally, you should be able to look at the [documentation](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.clipboard.getcontent?view=winrt-19041) and (at a basic level) convert the method names from CamelCase to snake_case and you'd be close. We're still working on improved code completion and VS Code integration but it is possible to get that to work already with some effort and that should also help. Anyway, here's a simple example:

```rust
use windows::application_model::data_transfer::*;

let content = DataPackage::new()?;
content.set_text("Rust/WinRT")?;
    
Clipboard::set_content(content)?;
Clipboard::flush()?;
```

If you stop there all should be well and you should be able to go to a text editor and paste the content. However, there's more:

```rust
let view = Clipboard::get_content()?;

for format in view.available_formats()? {
    println!("{}", format);
}

println!("{}", view.get_text_async()?.get()?);
```

This should all work until that last step. The trick is that to get the content from the view you need to call an async method. Normally this would work, but I think the DataTransfer API requires a UI thread and blocking on a UI thread with `get` is going to introduce a hang. So that will require support for #80

**Comment by tomocrafter** [comment]
Seems like this crate has revolved so much after this issue, now I want to know how to use Clipboard.GetContent with current version.
GetClipboardData is much complicated when want to decode to bitmap (and I'm new to windows api). How can I decode clipboard to bitmap without unsafe on current version?
