### ISSUE TITLE
Send and Sync Support

### ISSUE THREAD

**Issue by rylev** [microsoft/winrt-rs#193]
Currently all WinRT classes, interfaces, etc. are `!Send` and `!Sync`. Rust cannot automatically implement these marker traits are their underlying types are not `Send` and `Sync`. However, some WinRT types are indeed thread safe, namely those that implement `IAgileObject`. We should implement `Send` and `Sync` for these types.

**Comment by zachlute** [comment]
I've been meaning to play around with this codebase and simultaneously learn about WinRT, and picked this issue at semi-random this weekend to see if I could do an implementation. The implementation itself actually seems pretty straightforward, but it's not quite clear how to test it. So, a couple of questions:

1. Is there a known type in the existing WinRT projection that implements `IAgileObject`? This is surprisingly difficult to determine, since the metadata is essentially opaque and all of the documentation is about user objects.
1. If not, is there any documentation about implementing custom types? I found [documentation for the C++/WinRT projection](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/agile-objects), where deriving from `implements<MyType>` will automatically make something `IAgileObject` unless you opt out, but I couldn't find any examples of defining custom types in the current Rust codebase or in the Minesweeper example.

Additionally, while trying to learn about this, I came across the concept of tagging types with `MarshalingBehaviorAttribute(MarshalType.Agile)` in the metadata, which I believe is supposed to indicate that types like `Uri` can be safely marshaled between threads, but it's not quite clear to me whether that means those things should also be able to implement `Send` and `Sync` or if additional machinery is required.

**Comment by kennykerr** [comment]
In response to your questions:

1. You can query any object using `IUnknown`'s `QueryInterface` for `IAgileObject` at run time to determine whether it is agile. The is the only foolproof way to make this determination. 

2. Rust/WinRT doesn't yet support implementing WinRT types. That support will arrive in a [future milestone](https://github.com/microsoft/winrt-rs/milestone/4). For now, you can use C++/WinRT to implement WinRT types that you can then call from Rust/WinRT.

You can certainly use the `MarshalingBehaviorAttribute` attribute to query the agility of a given WinRT type. Note that there may well be many objects that are agile that do not carry this attribute. For example, you might have a WinRT class that has the `MarshalingBehaviorAttribute` attribute and asserts its agility and this class has a method that returns an `IVector<u32>`. Unless documented otherwise, you'd still have to rely on `IAgileObject` to determine whether this returned value is agile.

**Comment by zachlute** [comment]
@kennykerr Do you know an example of an existing type in the WinRT library that is `IAgileObject` that I could use to test with?

**Comment by kennykerr** [comment]
Windows.Foundation.Uri

**Comment by zachlute** [comment]
@kennykerr Okay, after poking at this a bit more, this is how I now understand this:

@rylev 's original issue suggests that we can generate `Send`/`Sync` implementations for WinRT types based on whether they implement `IAgileObject`, but your comment suggests that we can only know if they implement `IAgileObject` by querying the `IUnknown` interface of the instantiated object at runtime, which means that we *couldn't* generate the `Send`/`Sync` implementations based on that, because it can't be known at the time we're generating the implementations for the type.

If that's the case, then the *only* things we could generate at compile time are `Send`/`Sync` implementations for things with `MarshalingBehaviorAttribute(MarshalType.Agile)`, which is a weaker guarantee than `IAgileObject` implementation, but still valid.

Is that the case, or am I still misunderstanding something?

**Comment by kennykerr** [comment]
There are those that are known to be agile at compile time (based on metadata) and the rest may be agile but require a `to_agile` method that would return a `winrt::Agile<T>` that always implements `Send` and `Sync` since we can wrap a non-agile object inside an agile reference. That's basically what we do in C++/WinRT.

**Comment by zachlute** [comment]
@kennykerr Behold, my first attempt at this is up as a PR. Obviously open to any kind of feedback, as this was a real adventure, but I sure know way more about ECMA-335 and WinRT now just so I could get Enums reading correctly, so mission accomplished!
