### ISSUE TITLE
STATUS_STACK_BUFFER_OVERRUN on Application::start

### ISSUE THREAD

**Issue by bdbai** [microsoft/winrt-rs#214]
When I build and run the following code
```rust
use winrt::*;

import!(
    dependencies
        os
    types
        windows::ui::xaml::*
);

fn main() -> Result<()> {
    use windows::ui::xaml::{Application, ApplicationInitializationCallback};
    Application::start(ApplicationInitializationCallback::new(|_| Ok(())))
}
```
using rustc 1.44 stable toolchain
```powershell
PS > rustc +stable -vV
rustc 1.44.0 (49cae5576 2020-06-01)
binary: rustc
commit-hash: 49cae55760da0a43428eba73abcb659bb70cf2e4
commit-date: 2020-06-01
host: x86_64-pc-windows-msvc
release: 1.44.0
LLVM version: 9.0
```
with winrt-rs 0.7,
```toml
[dependencies]
winrt = "0.7"
```
the application exit with code 0xc0000409, STATUS_STACK_BUFFER_OVERRUN.
```powershell
PS > cargo run
......
    Finished dev [unoptimized + debuginfo] target(s) in 55.54s
     Running `target\debug\first-uwp.exe`
error: process didn't exit successfully: `target\debug\first-uwp.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

This is not expected because executing a UWP program (written in C++/WinRT) gives exit code 0. Is it a problem with delegate/closure in winrt-rs?

**Comment by kennykerr** [comment]
Thanks for reporting this issue. There are a few things to note here. Firstly, the equivalent code in a C++ app also crashes:

```C++
using namespace winrt;
using namespace Windows::UI::Xaml;

int main()
{
    Application::Start([](auto&&) { });
}
```

The problem is not with the language projection (either C++ or Rust) but with the usage of the Xaml API. The callback provided to the `Application::Start` method is required to create an Application-derived class, but in the example (both Rust and here in C++) the callback does nothing. I believe `Application::Start` also requires a packaged app and not merely a desktop app (you can use [Xaml Islands](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/xaml-islands) for that). So there's a bug in the Xaml application code because the Xaml API is being used in a way that is not supported. 

On the other hand, we believe that WinRT APIs should map to 100% safe Rust. Thus if you find a bug where you can violate Rust's guarantees in safe code, that is a bug in the backing implementation. In this case we need to work with the Xaml team to ensure that this usage error is reported via a WinRT error rather than simply crashing. We should open a bug with the Xaml team here:

https://github.com/microsoft/microsoft-ui-xaml/

**Comment by bdbai** [comment]
@kennykerr Thanks for the informative feedback. I am able to reproduce a similar crash with C++/WinRT Console Application. Once I changed the linker option `/SUBSYSTEM` to `/SUBSYSTEM:WINDOWS`, the C++/WinRT app did not crash any more. It should be the same case with Rust/WinRT.

Now that the issue is irrelavent to winrt-rs, please just close this issue.

**Comment by bdbai** [comment]
The issue has been reported to winui project, see https://github.com/microsoft/microsoft-ui-xaml/issues/2632.

**Comment by kennykerr** [comment]
I had a closer look and it turns out that the failure in Xaml is as a result of a fail-fast operation, which is guaranteed to avoid unwinding and immediately terminate the process in a safe way. I spoke with @rylev and we have concluded that this does not violate Rust's safety principles. There may well still be a usability issue here in that the developer experience isn't all that great, but that's a matter for the Xaml team to consider.

**Comment by ketsuban** [comment]
I'm getting this error value despite setting `#![windows_subsystem = "windows"]` at the top of my `main.rs`. My goal was to play around with the new XAML UI example, but it seems unrelated to that.

**Comment by kennykerr** [comment]
@ketsuban Did you try [this example](https://github.com/microsoft/windows-rs/tree/master/examples/xaml_app)? Xaml is not very forgiving if you try to use it without holding it just right.

**Comment by ketsuban** [comment]
That is exactly the code I'm using. The only difference is I didn't call my struct `MyApp` and I'm a little less free with wildcards (I checked, it made no difference).

**Comment by kennykerr** [comment]
And you used `register.cmd` to register the app and launched it from the Start menu? That particular example cannot be launched directly from `cargo run`.

**Comment by ketsuban** [comment]
Ah, I didn't try running from the Start menu. Do you know what needs to happen for it to work from `cargo run`?

**Comment by kennykerr** [comment]
For in-box Xaml I think this requires [Xaml islands](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/xaml-islands) - basically a bunch more setup code. For [WinUI](https://github.com/microsoft/microsoft-ui-xaml/) it might be simpler ([or not](https://github.com/microsoft/ProjectReunion/issues/866)) but I haven't tried that either. 

@riverar may have an example to share.

**Comment by ketsuban** [comment]
Okay, running from the Start menu isn't working either - a window appears with the logo file in it, then closes.

**Comment by kennykerr** [comment]
Debugging such registered apps is hard. If you can get something working with Xaml islands or WinUI in a regular executable it should be a lot easier to debug what might be going wrong on your system. Sorry I can't be more help - I don't know much about Xaml itself beyond the type system support to get the API callable in Rust.

**Comment by ketsuban** [comment]
Nevermind - I'd forgotten to change the executable name in the `AppxManifest.xml` file because my project isn't called `xaml_app`!

**Comment by tim-weis** [comment]
I got ~~nerd sniped~~ sidetracked into what turned out to be a Yak Shave of significant proportions. Partway through, I still managed to release [cargo-uwp](https://crates.io/crates/cargo-uwp), a Cargo custom command that sets up a UWP-ready Cargo package, alongside a build script that—among other things—keeps the `AppxManifest.xml` in sync with the artifacts.

The documentation is still a bit thin, but there is a short section on [debugging](https://crates.io/crates/cargo-uwp#debugging) a registered application. Maybe that is of help to you, @ketsuban.
