### ISSUE TITLE
cargo test failed on Windows 10 Chinese version

### ISSUE THREAD

**Issue by uhuntu** [microsoft/winrt-rs#264]
When I run test on Windows 10 Chinese version, cargo test failed.

```
     Running target\debug\deps\error-c13d9821a97c5cab.exe

running 3 tests
test from_hresult ... FAILED
test bad_uri ... FAILED
test originate ... ok

failures:

---- from_hresult stdout ----
thread 'from_hresult' panicked at 'assertion failed: `(left == right)`
  left: `"已中止操作"`,
 right: `"Operation aborted"`', tests\error.rs:13:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- bad_uri stdout ----
thread 'bad_uri' panicked at 'assertion failed: `(left == right)`
  left: `"INVALID 不是有效的绝对 URI。"`,
 right: `"INVALID is not a valid absolute URI."`', tests\error.rs:30:5


failures:
    bad_uri
    from_hresult

test result: FAILED. 1 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test error'
```

**Comment by rylev** [comment]
I'm assuming this is due to localization of the error messages. While I understand this is annoying when using a system not set to English, I'm not sure it's worth the trouble of actually addressing this since we're not testing Windows localization capabilities, merely that we get an error message - and the CI will run on a system set to English. @kennykerr do you have an opinion here? Is it possible to easily match against localized error messages?

**Comment by kennykerr** [comment]
I don't think it's worth the effort to localize tests. As long as winrt-rs itself works on non-English systems, we should be fine.

**Comment by rylev** [comment]
I'm going to close this. It's unfortunate, but we don't get a ton of benefit from making this work on systems that aren't set to English since we can assume the underlying APIs properly localize.
