### ISSUE TITLE
WIL for Rust

### ISSUE THREAD

**Issue by DrusTheAxe** [microsoft/winrt-rs#308]
[WIL](https://github.com/Microsoft/wil) is an invaluable library for Windows development using C++. Is there a Rust equivalent?

RAII helpers for Windows APIs like in win32_helpers.h, token_helpers.h and more would be welcome for Windows development using Rust. A 'WIL for Rust' moral equivalent or 'port to Rust language and idioms, to bring the same productivity gains to Rust as WIL brings to C++ development.

**Comment by kennykerr** [comment]
Thanks Howard. While I agree that there's value to having something like WIL For Rust developers, I'm not sure that it belongs in a single Rust crate. It's more likely that a family of crates will provide useful wrappers for individual Win32 APIs. We may also find that some are unnecessary depending on what overlap exists in Rust's standard library and many such [crates](https://crates.io/) may already exist.

**Comment by tim-weis** [comment]
There are two crates that attempt to provide safe wrappers that I'm aware of:

* [wio](https://crates.io/crates/wio)
* [winapi-util](https://crates.io/crates/winapi-util)

*wio* is published by [Peter Atashian](https://crates.io/users/retep998), maintainer of the [winapi](https://crates.io/crates/winapi) crate, and *winapi-util* by [Andrew Gallant](https://crates.io/users/BurntSushi). Both authors are very capable, yet neither crate is anywhere near complete, nor do they show any significant signs of life.

**Comment by kennykerr** [comment]
Closing as this is not specific to the Rust language projection. Feel free to keep the conversation going.

**Comment by DrusTheAxe** [comment]
@kennykerr Fair enough. I have no preference over the form. Just interested to see the relevant functionality also available to Rust developers. Is there a better venue for that discussion?

**Comment by kennykerr** [comment]
I'll create a dedicated repo and link to it here.

**Comment by justanotheranonymoususer** [comment]
I was also looking for something like WIL for rust. The closest thing I found is https://github.com/rodrigocfd/winsafe. It's great, but it's a single-man effort for a huge scope, it'd be great to have Microsoft to maintain/invest in such a project.

**Comment by kennykerr** [comment]
Many such helpers are now available including [windows-core](https://crates.io/crates/windows-core) with rich COM support, [windows-registry](https://crates.io/crates/windows-registry) with safe and efficient registry access, [windows-result](https://crates.io/crates/windows-result) with all kinds of error handling support, [windows-strings](https://crates.io/crates/windows-strings) that provides a bridge between Windows and Rust string types, [windows-version](https://crates.io/crates/windows-version) with reliable version information, and more is on the way. 

There's also support for automatically freeing various handle types akin to WIL wrappers (#3013).

**Comment by justanotheranonymoususer** [comment]
@kennykerr thanks, that's good progress, keep it up! All of it looks really good, I just needed to do some registry operations and looked for a good wrapper. But it seems very simplistic, for example, in my use case I need to pass `KEY_WOW64_64KEY `, is that possible? Should I create an issue?

Also, like in WIL, it'd be great to be able to have a lib to take care of APIs which return variable-length strings:
https://github.com/microsoft/wil/wiki/Win32-helpers#predefined-adapters-for-functions-that-return-variable-length-strings

**Comment by kennykerr** [comment]
> I need to pass KEY_WOW64_64KEY , is that possible? Should I create an issue?

Feel free to create an issue, otherwise I'll forget. 😊

**Comment by justanotheranonymoususer** [comment]
Created, thanks. Here's another example that I encountered recently: using `TaskDialogIndirect`. You have an example for it here:

https://github.com/microsoft/windows-rs/blob/1a3f15bee39e1557f8fa24c240d5ee6d87dfd9b9/crates/samples/windows/task_dialog/src/main.rs#L27

Note how the whole code is `unsafe` and the callback must be `extern "system"`. Compare it to [the winsafe version](https://github.com/rodrigocfd/winsafe/blob/f6b988e65c1f044ec1f1157c53a47205f6fbf86f/src/comctl/funcs.rs#L96-L114):

```rust
use winsafe::{self as w, prelude::*, co};

w::TaskDialogIndirect(&w::TASKDIALOGCONFIG {
    common_buttons: co::TDCBF::OK,
    window_title: Some("Title"),
    content: Some("Content"),
    callback: Some(Box::new(|hwnd: &w::HWND, tdn: w::Tdn| -> co::HRESULT {
        match tdn {
            w::Tdn::Created => println!("created"),
            _ => {},
        }
        co::HRESULT::S_OK
    })),
    ..Default::default()
})?;
```
Safe, typed, beautiful, with a native lambda which can capture variables etc. Is something like this in scope for this repo?

**Comment by jdoubleu** [comment]
Wanted to join the discussion, because I was missing a few features from these crates and stumbled upon this discussion.

> It's more likely that a family of crates will provide useful wrappers for individual Win32 APIs. We may also find that some are unnecessary depending on what overlap exists in Rust's standard library and many such [crates](https://crates.io/) may already exist. On the other hand, perhaps we just need a neat collection of Windows-specific helpers in a single crate for systems programming on Windows.

While the organization of those helpers might be up for discussion, I'd rather prefer them being provided by Microsoft's official collection of rust crates rather than thirdparty vendors. This not only provides more trust in these helpers, but also makes them more visible and approachable to (new) users of the libraries.

I'd also agree that in general, higher-level wrappers should be written, that integrate the respective API's even better into Rust. Yet low-level helpers are still useful to aid writing those wrappers.

I've compiled an incomplete list of features I'd love to see:
1. Calling a function twice. First to get the needed size of the buffer, then to actually fill the buffer. That discussion has already been moved to https://github.com/microsoft/windows-rs/issues/3475. Btw., is there a name for this pattern or how would you call it?
   1. https://github.com/microsoft/windows-rs/issues/3475#issuecomment-2652084149 already notes that there are some subtle differences in these APIs. Another is that some functions may return an _expected_ error. It would be nice to have some sort of macro that could simply swallow/ignore all expected errors (the user defines), instead of needing to apply some rust boilerplate (e.g. a `match`).
2. Some functions, e.g. [`GetLogicalDriveStringsW`](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getlogicaldrivestringsw) return a list of null-terminated strings into a buffer. It would be nice to have a native Iterator, that properly handles these lists, and also allows them to be converted into other types (e.g. `Vec<&str>` or `Vec<String>`, etc.).
3. A common pattern when requesting structured and variable-length data from an API is just to allocate a buffer where a struct is used as a header and variable-length data is just concatenated (see trailing `Type[1]` members). That is very common with IOCTL's. For example the [`IOCTL_DISK_GET_DRIVE_GEOMETRY_EX`](https://learn.microsoft.com/en-us/windows/win32/api/winioctl/ni-winioctl-ioctl_disk_get_drive_geometry_ex) IOCTL that returns a [`DRIVE_LAYOUT_INFORMATION_EX`](https://learn.microsoft.com/en-us/windows/win32/api/winioctl/ns-winioctl-drive_layout_information_ex) struct, where that struct is used as a header, specifying the count in its `PartitionCount` member and marking the start of the entries with `PartitionEntry`.
   *  Specifically when needing to provide such a buffer as input, one would technically have to assure, that the buffer is properly aligned for that struct/header. A helper could prevent mistakes here and make it easier to access the header and data without needing to perform manual pointer casting.

I'm happy to contribute and help implement these mentioned features, if welcome?
