### ISSUE TITLE
Use OS-specific path joiners in include_bindings!()

### ISSUE THREAD

**Issue by Enigmatrix** [microsoft/winrt-rs#376]
`include_bindings!()` uses a Windows-based path join, so building on Linux is out of the question. Need to change them to work on Linux as well.

https://github.com/microsoft/winrt-rs/blob/83669a4f1ad7b41cffb11d2243d824b2fbdba718/src/macros.rs#L2-L7

**Comment by Enigmatrix** [comment]
after replacing the slashes, there are other errors. e.g.
```
 `...` is not a known namespace.
```
so this isn't really an urgent issue .-.

**Comment by kennykerr** [comment]
What's the rationale for building on Linux?

**Comment by kennykerr** [comment]
Ah, well free to to contribute a PR with any _minor_ changes needed to support Linux compilation. Sorry, I have no experience with Linux so that's not something I'd be able to do. If you do decide to try this, adding a [Linux build step](https://github.com/microsoft/winrt-rs/blob/master/.github/workflows/build.yml) would also be helpful to avoid regressions.

**Comment by kennykerr** [comment]
Feel free to reopen if there's interest in exploring this further.
